/**
 * @fileoverview gRPC-Web generated client stub for api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: cluster_info_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as cluster_info_service_pb from './cluster_info_service_pb'; // proto import: "cluster_info_service.proto"


export class ClusterInfoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetClusterInfo = new grpcWeb.MethodDescriptor(
    '/api.ClusterInfoService/GetClusterInfo',
    grpcWeb.MethodType.UNARY,
    cluster_info_service_pb.ClusterInfoRequest,
    cluster_info_service_pb.ClusterInfoResponse,
    (request: cluster_info_service_pb.ClusterInfoRequest) => {
      return request.serializeBinary();
    },
    cluster_info_service_pb.ClusterInfoResponse.deserializeBinary
  );

  getClusterInfo(
    request: cluster_info_service_pb.ClusterInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<cluster_info_service_pb.ClusterInfoResponse>;

  getClusterInfo(
    request: cluster_info_service_pb.ClusterInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: cluster_info_service_pb.ClusterInfoResponse) => void): grpcWeb.ClientReadableStream<cluster_info_service_pb.ClusterInfoResponse>;

  getClusterInfo(
    request: cluster_info_service_pb.ClusterInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: cluster_info_service_pb.ClusterInfoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.ClusterInfoService/GetClusterInfo',
        request,
        metadata || {},
        this.methodDescriptorGetClusterInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.ClusterInfoService/GetClusterInfo',
    request,
    metadata || {},
    this.methodDescriptorGetClusterInfo);
  }

}

